// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	types "github.com/godaddy-x/wallet-adapter/types"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto(in *jlexer.Lexer, out *SubmitRawTransactionRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Txid = string(in.String())
			}
		case "wxid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Wxid = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "from":
			if in.IsNull() {
				in.Skip()
				out.From = nil
			} else {
				in.Delim('[')
				if out.From == nil {
					if !in.IsDelim(']') {
						out.From = make([]string, 0, 4)
					} else {
						out.From = []string{}
					}
				} else {
					out.From = (out.From)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.From = append(out.From, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "to":
			if in.IsNull() {
				in.Skip()
				out.To = nil
			} else {
				in.Delim('[')
				if out.To == nil {
					if !in.IsDelim(']') {
						out.To = make([]string, 0, 4)
					} else {
						out.To = []string{}
					}
				} else {
					out.To = (out.To)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.To = append(out.To, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "decimal":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimal = int32(in.Int32())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = uint64(in.Uint64())
			}
		case "txAction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAction = string(in.String())
			}
		case "confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirm = int64(in.Int64())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "isMemo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsMemo = bool(in.Bool())
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "received":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Received = bool(in.Bool())
			}
		case "submitTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubmitTime = int64(in.Int64())
			}
		case "confirmTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmTime = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto(out *jwriter.Writer, in SubmitRawTransactionRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Txid))
	}
	{
		const prefix string = ",\"wxid\":"
		out.RawString(prefix)
		out.String(string(in.Wxid))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		if in.From == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.From {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.To {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"decimal\":"
		out.RawString(prefix)
		out.Int32(int32(in.Decimal))
	}
	{
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TxType))
	}
	{
		const prefix string = ",\"txAction\":"
		out.RawString(prefix)
		out.String(string(in.TxAction))
	}
	{
		const prefix string = ",\"confirm\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirm))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"isMemo\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsMemo))
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"received\":"
		out.RawString(prefix)
		out.Bool(bool(in.Received))
	}
	{
		const prefix string = ",\"submitTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.SubmitTime))
	}
	{
		const prefix string = ",\"confirmTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ConfirmTime))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitRawTransactionRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitRawTransactionRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitRawTransactionRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitRawTransactionRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto1(in *jlexer.Lexer, out *SubmitRawTransactionReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "pendingSignTx":
			if in.IsNull() {
				in.Skip()
				out.PendingSignTx = nil
			} else {
				if out.PendingSignTx == nil {
					out.PendingSignTx = new(types.PendingSignTx)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.PendingSignTx).UnmarshalEasyJSON(in)
				}
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto1(out *jwriter.Writer, in SubmitRawTransactionReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pendingSignTx\":"
		out.RawString(prefix[1:])
		if in.PendingSignTx == nil {
			out.RawString("null")
		} else {
			(*in.PendingSignTx).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitRawTransactionReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitRawTransactionReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitRawTransactionReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitRawTransactionReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto1(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto2(in *jlexer.Lexer, out *SubmitRawTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "appID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "rawHex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHex = string(in.String())
			}
		case "rawHexSig":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHexSig = string(in.String())
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReqSigs = uint64(in.Uint64())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "sigCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SigCount = int64(in.Int64())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.To = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					(out.To)[key] = v7
					in.WantComma()
				}
				in.Delim('}')
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "sigParts":
			if in.IsNull() {
				in.Skip()
				out.SigParts = nil
			} else {
				in.Delim('[')
				if out.SigParts == nil {
					if !in.IsDelim(']') {
						out.SigParts = make([]SigParts, 0, 1)
					} else {
						out.SigParts = []SigParts{}
					}
				} else {
					out.SigParts = (out.SigParts)[:0]
				}
				for !in.IsDelim(']') {
					var v8 SigParts
					if in.IsNull() {
						in.Skip()
					} else {
						(v8).UnmarshalEasyJSON(in)
					}
					out.SigParts = append(out.SigParts, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "errorMsg":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ErrorMsg = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v9 string
					if in.IsNull() {
						in.Skip()
					} else {
						v9 = string(in.String())
					}
					(out.ErrorMsg)[key] = v9
					in.WantComma()
				}
				in.Delim('}')
			}
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "account":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Account).UnmarshalEasyJSON(in)
			}
		case "dataType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataType = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto2(out *jwriter.Writer, in SubmitRawTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"appID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"rawHex\":"
		out.RawString(prefix)
		out.String(string(in.RawHex))
	}
	{
		const prefix string = ",\"rawHexSig\":"
		out.RawString(prefix)
		out.String(string(in.RawHexSig))
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ReqSigs))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"sigCount\":"
		out.RawString(prefix)
		out.Int64(int64(in.SigCount))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v10First := true
			for v10Name, v10Value := range in.To {
				if v10First {
					v10First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v10Name))
				out.RawByte(':')
				out.String(string(v10Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"sigParts\":"
		out.RawString(prefix)
		if in.SigParts == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.SigParts {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"errorMsg\":"
		out.RawString(prefix)
		if in.ErrorMsg == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v13First := true
			for v13Name, v13Value := range in.ErrorMsg {
				if v13First {
					v13First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v13Name))
				out.RawByte(':')
				out.String(string(v13Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"account\":"
		out.RawString(prefix)
		(in.Account).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"dataType\":"
		out.RawString(prefix)
		out.Int64(int64(in.DataType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitRawTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitRawTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitRawTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitRawTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto2(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto3(in *jlexer.Lexer, out *SmartCoinInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contractID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractID = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto3(out *jwriter.Writer, in SmartCoinInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contractID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContractID))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Decimals))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartCoinInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartCoinInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartCoinInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartCoinInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto3(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto4(in *jlexer.Lexer, out *SigParts) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "sig":
			if in.IsNull() {
				in.Skip()
				out.Sig = nil
			} else {
				in.Delim('[')
				if out.Sig == nil {
					if !in.IsDelim(']') {
						out.Sig = make([]KeySig, 0, 0)
					} else {
						out.Sig = []KeySig{}
					}
				} else {
					out.Sig = (out.Sig)[:0]
				}
				for !in.IsDelim(']') {
					var v14 KeySig
					if in.IsNull() {
						in.Skip()
					} else {
						(v14).UnmarshalEasyJSON(in)
					}
					out.Sig = append(out.Sig, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto4(out *jwriter.Writer, in SigParts) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"sig\":"
		out.RawString(prefix)
		if in.Sig == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v15, v16 := range in.Sig {
				if v15 > 0 {
					out.RawByte(',')
				}
				(v16).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SigParts) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SigParts) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SigParts) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SigParts) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto4(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto5(in *jlexer.Lexer, out *KeySig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "derivedPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DerivedPath = string(in.String())
			}
		case "eccType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EccType = uint32(in.Uint32())
			}
		case "inputIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InputIndex = int64(in.Int64())
			}
		case "msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "nonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "signed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signed = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "isImport":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsImport = int64(in.Int64())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "rsv":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rsv = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto5(out *jwriter.Writer, in KeySig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"derivedPath\":"
		out.RawString(prefix)
		out.String(string(in.DerivedPath))
	}
	{
		const prefix string = ",\"eccType\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.EccType))
	}
	{
		const prefix string = ",\"inputIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.InputIndex))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	{
		const prefix string = ",\"nonce\":"
		out.RawString(prefix)
		out.String(string(in.Nonce))
	}
	{
		const prefix string = ",\"signed\":"
		out.RawString(prefix)
		out.String(string(in.Signed))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"isImport\":"
		out.RawString(prefix)
		out.Int64(int64(in.IsImport))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"rsv\":"
		out.RawString(prefix)
		out.Bool(bool(in.Rsv))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v KeySig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KeySig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *KeySig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KeySig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto5(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto6(in *jlexer.Lexer, out *GetTransactionFeeEstimatedRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "gasLimit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GasLimit = string(in.String())
			}
		case "gasPrice":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GasPrice = string(in.String())
			}
		case "fee":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fee = string(in.String())
			}
		case "mainBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainBalance = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto6(out *jwriter.Writer, in GetTransactionFeeEstimatedRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"gasLimit\":"
		out.RawString(prefix[1:])
		out.String(string(in.GasLimit))
	}
	{
		const prefix string = ",\"gasPrice\":"
		out.RawString(prefix)
		out.String(string(in.GasPrice))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.String(string(in.Fee))
	}
	{
		const prefix string = ",\"mainBalance\":"
		out.RawString(prefix)
		out.String(string(in.MainBalance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetTransactionFeeEstimatedRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetTransactionFeeEstimatedRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetTransactionFeeEstimatedRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetTransactionFeeEstimatedRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto6(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto7(in *jlexer.Lexer, out *GetTransactionFeeEstimatedReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = string(in.String())
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = int32(in.Int32())
			}
		case "tokenAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokenAddress = string(in.String())
			}
		case "tokenDecimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokenDecimals = int32(in.Int32())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto7(out *jwriter.Writer, in GetTransactionFeeEstimatedReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int32(int32(in.Decimals))
	}
	{
		const prefix string = ",\"tokenAddress\":"
		out.RawString(prefix)
		out.String(string(in.TokenAddress))
	}
	{
		const prefix string = ",\"tokenDecimals\":"
		out.RawString(prefix)
		out.Int32(int32(in.TokenDecimals))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetTransactionFeeEstimatedReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetTransactionFeeEstimatedReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetTransactionFeeEstimatedReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetTransactionFeeEstimatedReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto7(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto8(in *jlexer.Lexer, out *GetTransactionCountOnChainRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "nonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto8(out *jwriter.Writer, in GetTransactionCountOnChainRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nonce\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Nonce))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetTransactionCountOnChainRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetTransactionCountOnChainRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetTransactionCountOnChainRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetTransactionCountOnChainRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto8(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto9(in *jlexer.Lexer, out *GetTransactionCountOnChainReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto9(out *jwriter.Writer, in GetTransactionCountOnChainReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetTransactionCountOnChainReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetTransactionCountOnChainReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetTransactionCountOnChainReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetTransactionCountOnChainReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto9(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto10(in *jlexer.Lexer, out *FeesSupportAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "fixSupportAmount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FixSupportAmount = string(in.String())
			}
		case "feesSupportScale":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeesSupportScale = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto10(out *jwriter.Writer, in FeesSupportAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"fixSupportAmount\":"
		out.RawString(prefix)
		out.String(string(in.FixSupportAmount))
	}
	{
		const prefix string = ",\"feesSupportScale\":"
		out.RawString(prefix)
		out.String(string(in.FeesSupportScale))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FeesSupportAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FeesSupportAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FeesSupportAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FeesSupportAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto10(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto11(in *jlexer.Lexer, out *CreateTradeRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "pendingSignTx":
			if in.IsNull() {
				in.Skip()
				out.PendingSignTx = nil
			} else {
				in.Delim('[')
				if out.PendingSignTx == nil {
					if !in.IsDelim(']') {
						out.PendingSignTx = make([]*types.PendingSignTx, 0, 8)
					} else {
						out.PendingSignTx = []*types.PendingSignTx{}
					}
				} else {
					out.PendingSignTx = (out.PendingSignTx)[:0]
				}
				for !in.IsDelim(']') {
					var v17 *types.PendingSignTx
					if in.IsNull() {
						in.Skip()
						v17 = nil
					} else {
						if v17 == nil {
							v17 = new(types.PendingSignTx)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v17).UnmarshalEasyJSON(in)
						}
					}
					out.PendingSignTx = append(out.PendingSignTx, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto11(out *jwriter.Writer, in CreateTradeRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pendingSignTx\":"
		out.RawString(prefix[1:])
		if in.PendingSignTx == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.PendingSignTx {
				if v18 > 0 {
					out.RawByte(',')
				}
				if v19 == nil {
					out.RawString("null")
				} else {
					(*v19).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTradeRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTradeRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTradeRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTradeRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto11(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto12(in *jlexer.Lexer, out *CreateTradeReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.To = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v20 string
					if in.IsNull() {
						in.Skip()
					} else {
						v20 = string(in.String())
					}
					(out.To)[key] = v20
					in.WantComma()
				}
				in.Delim('}')
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto12(out *jwriter.Writer, in CreateTradeReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v21First := true
			for v21Name, v21Value := range in.To {
				if v21First {
					v21First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v21Name))
				out.RawByte(':')
				out.String(string(v21Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTradeReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTradeReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTradeReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTradeReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto12(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto13(in *jlexer.Lexer, out *CreateSummaryTxReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "minTransfer":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinTransfer = string(in.String())
			}
		case "retainedBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RetainedBalance = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "addressStartIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressStartIndex = int64(in.Int64())
			}
		case "addressLimit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressLimit = int64(in.Int64())
			}
		case "confirms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirms = int64(in.Int64())
			}
		case "feesSupportAccount":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.FeesSupportAccount).UnmarshalEasyJSON(in)
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto13(out *jwriter.Writer, in CreateSummaryTxReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"minTransfer\":"
		out.RawString(prefix)
		out.String(string(in.MinTransfer))
	}
	{
		const prefix string = ",\"retainedBalance\":"
		out.RawString(prefix)
		out.String(string(in.RetainedBalance))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"addressStartIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressStartIndex))
	}
	{
		const prefix string = ",\"addressLimit\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressLimit))
	}
	{
		const prefix string = ",\"confirms\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirms))
	}
	{
		const prefix string = ",\"feesSupportAccount\":"
		out.RawString(prefix)
		(in.FeesSupportAccount).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSummaryTxReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSummaryTxReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSummaryTxReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSummaryTxReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto13(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto14(in *jlexer.Lexer, out *CoinInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "isContract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsContract = bool(in.Bool())
			}
		case "contractID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractID = string(in.String())
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "contractABI":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractABI = string(in.String())
			}
		case "contract":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Contract).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto14(out *jwriter.Writer, in CoinInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"isContract\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsContract))
	}
	{
		const prefix string = ",\"contractID\":"
		out.RawString(prefix)
		out.String(string(in.ContractID))
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"contractABI\":"
		out.RawString(prefix)
		out.String(string(in.ContractABI))
	}
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix)
		(in.Contract).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CoinInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CoinInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CoinInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CoinInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto14(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto15(in *jlexer.Lexer, out *AssetsAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = uint64(in.Uint64())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HdPath = string(in.String())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "ownerKeys":
			if in.IsNull() {
				in.Skip()
				out.OwnerKeys = nil
			} else {
				in.Delim('[')
				if out.OwnerKeys == nil {
					if !in.IsDelim(']') {
						out.OwnerKeys = make([]string, 0, 4)
					} else {
						out.OwnerKeys = []string{}
					}
				} else {
					out.OwnerKeys = (out.OwnerKeys)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.OwnerKeys = append(out.OwnerKeys, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "addressIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressIndex = int64(in.Int64())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReqSigs = int64(in.Int64())
			}
		case "isTrust":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsTrust = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto15(out *jwriter.Writer, in AssetsAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HdPath))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"ownerKeys\":"
		out.RawString(prefix)
		if in.OwnerKeys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.OwnerKeys {
				if v23 > 0 {
					out.RawByte(',')
				}
				out.String(string(v24))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"addressIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressIndex))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReqSigs))
	}
	{
		const prefix string = ",\"isTrust\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsTrust))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AssetsAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AssetsAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComGodaddyXWalletMpcTssWalletapiDto15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AssetsAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AssetsAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComGodaddyXWalletMpcTssWalletapiDto15(l, v)
}
