// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto(in *jlexer.Lexer, out *TradeLogResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "appID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "txID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "txAction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAction = string(in.String())
			}
		case "fromAddress":
			if in.IsNull() {
				in.Skip()
				out.FromAddress = nil
			} else {
				in.Delim('[')
				if out.FromAddress == nil {
					if !in.IsDelim(']') {
						out.FromAddress = make([]string, 0, 4)
					} else {
						out.FromAddress = []string{}
					}
				} else {
					out.FromAddress = (out.FromAddress)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.FromAddress = append(out.FromAddress, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "fromAddressV":
			if in.IsNull() {
				in.Skip()
				out.FromAddressV = nil
			} else {
				in.Delim('[')
				if out.FromAddressV == nil {
					if !in.IsDelim(']') {
						out.FromAddressV = make([]string, 0, 4)
					} else {
						out.FromAddressV = []string{}
					}
				} else {
					out.FromAddressV = (out.FromAddressV)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.FromAddressV = append(out.FromAddressV, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "toAddress":
			if in.IsNull() {
				in.Skip()
				out.ToAddress = nil
			} else {
				in.Delim('[')
				if out.ToAddress == nil {
					if !in.IsDelim(']') {
						out.ToAddress = make([]string, 0, 4)
					} else {
						out.ToAddress = []string{}
					}
				} else {
					out.ToAddress = (out.ToAddress)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.ToAddress = append(out.ToAddress, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "toAddressV":
			if in.IsNull() {
				in.Skip()
				out.ToAddressV = nil
			} else {
				in.Delim('[')
				if out.ToAddressV == nil {
					if !in.IsDelim(']') {
						out.ToAddressV = make([]string, 0, 4)
					} else {
						out.ToAddressV = []string{}
					}
				} else {
					out.ToAddressV = (out.ToAddressV)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.ToAddressV = append(out.ToAddressV, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "isContract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsContract = bool(in.Bool())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = int64(in.Int64())
			}
		case "isMemo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsMemo = bool(in.Bool())
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "applyTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ApplyTime = int64(in.Int64())
			}
		case "blockTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockTime = int64(in.Int64())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = int64(in.Int64())
			}
		case "dealStatus":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DealStatus = int64(in.Int64())
			}
		case "notifyStatus":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NotifyStatus = int64(in.Int64())
			}
		case "contractName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractName = string(in.String())
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = string(in.String())
			}
		case "balanceMode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BalanceMode = int64(in.Int64())
			}
		case "outputIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OutputIndex = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto(out *jwriter.Writer, in TradeLogResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"appID\":"
		out.RawString(prefix)
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"txID\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"txAction\":"
		out.RawString(prefix)
		out.String(string(in.TxAction))
	}
	{
		const prefix string = ",\"fromAddress\":"
		out.RawString(prefix)
		if in.FromAddress == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.FromAddress {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"fromAddressV\":"
		out.RawString(prefix)
		if in.FromAddressV == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.FromAddressV {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"toAddress\":"
		out.RawString(prefix)
		if in.ToAddress == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.ToAddress {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.String(string(v10))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"toAddressV\":"
		out.RawString(prefix)
		if in.ToAddressV == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.ToAddressV {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"isContract\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsContract))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockHeight))
	}
	{
		const prefix string = ",\"isMemo\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsMemo))
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"applyTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ApplyTime))
	}
	{
		const prefix string = ",\"blockTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockTime))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int64(int64(in.Decimals))
	}
	{
		const prefix string = ",\"dealStatus\":"
		out.RawString(prefix)
		out.Int64(int64(in.DealStatus))
	}
	{
		const prefix string = ",\"notifyStatus\":"
		out.RawString(prefix)
		out.Int64(int64(in.NotifyStatus))
	}
	{
		const prefix string = ",\"contractName\":"
		out.RawString(prefix)
		out.String(string(in.ContractName))
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix)
		out.String(string(in.Success))
	}
	{
		const prefix string = ",\"balanceMode\":"
		out.RawString(prefix)
		out.Int64(int64(in.BalanceMode))
	}
	{
		const prefix string = ",\"outputIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.OutputIndex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TradeLogResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TradeLogResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TradeLogResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TradeLogResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto(l, v)
}
func easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto1(in *jlexer.Lexer, out *FindTradeLogRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]TradeLogResult, 0, 0)
					} else {
						out.Result = []TradeLogResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v13 TradeLogResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Limit).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto1(out *jwriter.Writer, in FindTradeLogRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Result {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		(in.Limit).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindTradeLogRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindTradeLogRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindTradeLogRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindTradeLogRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto1(l, v)
}
func easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto2(in *jlexer.Lexer, out *FindTradeLogReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "txID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = int64(in.Int64())
			}
		case "txAction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAction = string(in.String())
			}
		case "ContractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "sort":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sort = int(in.Int())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto2(out *jwriter.Writer, in FindTradeLogReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"txID\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockHeight))
	}
	{
		const prefix string = ",\"txAction\":"
		out.RawString(prefix)
		out.String(string(in.TxAction))
	}
	{
		const prefix string = ",\"ContractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"sort\":"
		out.RawString(prefix)
		out.Int(int(in.Sort))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindTradeLogReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindTradeLogReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF5a7a3cEncodeGithubComGodaddyXWalletMpcTssWalletapiDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindTradeLogReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindTradeLogReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF5a7a3cDecodeGithubComGodaddyXWalletMpcTssWalletapiDto2(l, v)
}
